import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { LoadingProvider } from "../components/loading/loading_context";
import LoadingModal from "../components/loading/loading_modal";
import { AddressProvider } from "@/components/address/address_context";
import { Metadata } from "next";
import { AppConfig } from "@/shared/app_config";
import { ShoppingCardProvider } from "@/components/context_api/shopping_card_context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Cmp',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  console.log("RootLayoutRootLayout");
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <TokenProvider> */}
        <AddressProvider>
          <LoadingProvider>
            <LoadingModal />
            <ShoppingCardProvider>
              {children}
            </ShoppingCardProvider>
          </LoadingProvider>
        </AddressProvider>
        {/* </TokenProvider> */}
        <Toaster />
      </body>
    </html>
  );
}
